### ISSUE TITLE
Documentation Website Broken

### ISSUE THREAD

**Issue by rosscastle** [ajaramillomoreno/wk_spectra#1]
Hello,

I'd like to use this code but I can't access the documentation as the website doesn't seem to exist anymore.

Thanks,

**Comment by ajaramillomoreno** [comment]
Hi,

Thank you for your interest in my package, it is actually an unfinished work because I have not got funding to keep working on it. The package is completely functional but the documentation is missing. I attach here a small example of how to use the package I hope it makes sense. 

https://file.io/3koQ0n

Best,

**Comment by rosscastle** [comment]
Hi Alejandro,

Thank you for the pdf, hopefully I will figure it out.

I am sorry the funding stopped, it looks to be a very useful piece of software, especially in Python.

Best,

Ross

________________________________

**Comment by ajaramillomoreno** [comment]
Hi Ross,

Thank you again for your interest in my package.

Please do not hesitate to write to me with your questions, I promise to reply although with the current situation it may take me a few days. With the Coronavirus outbreak, everything has been more difficult since I have restricted access to my computer on campus.

Please contact me to my email ajaramillomoreno@gmail.com

Best,

Alejandro

**Comment by rosscastle** [comment]
Hi Alejandro,

Sorry to bother you again.

The link you attached seems to have stopped working?

If you could send again I would be very grateful!

Thanks,

Ross

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
